#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 13 22:20:20 2020

@author: laraconboy
"""

num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = int(num1) + int(num2) 

print(result)

num1 = input("Enter a number: ")
num2 = input("Enter another number")
result = float(num1) + float(num2)

print(result)